# Generated by Django 2.2.4 on 2019-11-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0002_auto_20191108_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='actual',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
