# Generated by Django 2.2.4 on 2019-11-08 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0003_record_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='observer',
            field=models.ManyToManyField(blank=True, related_name='habits_observing', to=settings.AUTH_USER_MODEL),
        ),
    ]
